const router =[
    {
        title:"控制台",
        icon:'index',
        key:'/index'
    },
    {
        title:'患者管理',
        icon:'laptop',
        key:'/index/user',
        child:[
            {key:'/index/user/list',
            title:'患者信息',
            icon:''},
        ]
    },
    {
        title:'医生管理',
        icon:'doctor',
        key:'/index/doctor',
        child:[
            {key:'/index/doctor/list',
            title:'医生列表',
            icon:'laptop'},
        ]
    },
    {
        title:'科室管理',
        icon:'laptop',
        key:'/index/depart',
        child:[
            {key:'/index/depart/list',
            title:'科室列表',
            icon:''},
        ]
    },
    {
        title:'项目管理',
        icon:'laptop',
        key:'/index/project',
        child:[
            {key:'/index/project/list',
            title:'项目列表',
            icon:''},
        ]
    },
    {
        title:'医生排班',
        icon:'laptop',
        key:'/index/doctorschedule',
        child:[
            {key:'/index/doctorschedule/list',
            title:'科室排班',
            icon:''},
        ]
    },
    {
        title:'预约信息',
        icon:'laptop',
        key:'/index/registerinformation',
        child:[
            {key:'/index/registerinformation/list',
            title:'预约列表',
            icon:''},
        ]
    }
]
export default router;